# Generated by Django 4.1.3 on 2023-08-13 20:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_categoryuser_category_subscriber'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryuser',
            unique_together={('user', 'category')},
        ),
    ]
